apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: fcovillegast@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
name: guestbook-letsencrypt-staging
annotations:
  kubernetes.io/ingress.class: nginx
  cert-manager.io/cluster-issuer: letsencrypt-staging
  cert-manager.io/acme-challenge-type: http01
spec:
tls:
  - hosts:
      - taxisbahia.cl
      secretName: guestbook-secret-name
rules:
  - host: taxisbahia.cl
      http:
      paths:
        - backend:
            serviceName: taxisbahia
            servicePort: 8080