apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: fcovillegast@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx
        selector: {}

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: esp-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-staging
  labels:
    type: endpoints-app
spec:
  tls:
    - hosts:
        - taxisbahia.cl
      secretName: esp-tls
  rules:
    - host: taxisbahia.cl
      http:
        paths:
          - backend:
              serviceName: esp-srv
              servicePort: 8080