apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: mini-api
spec:
  acme:
    # Staging API
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: fcovillegast@gmail.com
    privateKeySecretRef:
      name: account-key-staging
    solvers:
      - http01:
          ingress:
            class: nginx
---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: miniapi-staging
  namespace: mini-api
spec:
  secretName: miniapi-staging-certificate
  issuerRef:
    name: letsencrypt-staging
  dnsNames:
    - taxisbahia.cl

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingressrule
  namespace: mini-api
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/issuer: "letsencrypt-staging"
spec:
  tls:
    - hosts:
        - taxisbahia.cl
      secretName: miniapi-staging-certificate
  rules:
    - host: taxisbahia.cl
      http:
        paths:
          - path: /
            backend:
              serviceName: taxisbahia
              servicePort: 8080