apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxisbahia
  namespace: mini-api
  labels:
    type: endpoints-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taxisbahia
  template:
    metadata:
      labels:
        app: taxisbahia
    spec:
      containers:
        - name: taxisbahia
          image: gcr.io/innate-beacon-797/taxisbahia:1.0.131
          imagePullPolicy: Always
          ports:
            - containerPort: 8080