apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxisbahia
  labels:
    type: endpoints-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taxisbahia
  template:
    metadata:
      labels:
        app: taxisbahia
    spec:
      containers:
        - name: taxisbahia
          image: gcr.io/innate-beacon-797/taxisbahia:1.0.131
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: taxibahia