apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-docker
  name: hello-docker-svc
  namespace: default
spec:
  ports:
    - port: 80
        protocol: TCP
        targetPort: 80
  selector:
    app: hello-docker
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}