apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echo-ingress
spec:
  rules:
    - host: taxisbahia.cl
      http:
        paths:
          - backend:
              serviceName: echo1
              servicePort: 80