apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: esp-tls
  namespace: default
spec:
  secretName: esp-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: taxisbahia.cl
  dnsNames:
  - taxisbahia.cl
  acme:
    config:
    - http01:
        ingress: esp-ingress
      domains:
      - taxisbahia.cl