apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    kubernetes.io/ingress.class: nginx
  name: esp-ingress
spec:
  rules:
    - host: taxisbahia.cl
      http:
        paths:
          - path: /restsvc(/|$)(.*)
            backend:
              serviceName: taxisbahia
              servicePort: 8080
  tls:
    - hosts:
        - taxisbahia.cl
      secretName: secret
