
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxisbahia
  labels:
    type: endpoints-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taxisbahia
  template:
    metadata:
      labels:
        app: taxisbahia
    spec:
      containers:
        - name: taxisbahia
          image: gcr.io/innate-beacon-797/taxisbahia:1.0.131
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: taxisbahia
  labels:
    type: esp-srv
spec:
  type: LoadBalancer
  loadBalancerIP: 35.239.238.163
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: taxisbahia

---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: certificate-name
spec:
  secretName: tls-cert
  duration: 24h
  renewBefore: 12h
  commonName: taxisbahia.cl
  dnsNames:
    - taxisbahia.cl
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer

---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: fcovillegast@gmail.com
    privateKeySecretRef:
      name: letsencrypt-private-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx
        selector: {}

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/acme-challenge-type: http01
    certmanager.k8s.io/cluster-issuer: letsencrypt
  name: ingress-rule
  namespace: default
spec:
  rules:
    - host: taxisbahia.cl
      http:
        paths:
          - backend:
              serviceName: taxisbahia
              servicePort: 80
  tls:
    - hosts:
        - taxisbahia.cl
      secretName: tls-cert