apiVersion: cert-manager.io/v1alpha2
kind: Certificate
  metadata:
    name: certificate-name
spec:
  secretName: tls-cert
  duration: 24h
  renewBefore: 12h
  commonName: taxisbahia.cl
  dnsNames:
    - taxisbahia.cl
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer